[package]
name = "fimfareader"
version = "0.1.0"
authors = ["Joakim Soderlund <joakim.soderlund@gmail.com>"]
edition = "2024"

[workspace]
members = [
    "cli",
    "query",
    "search",
]

default-members = [
    "cli",
]

[profile.release]
lto = true

[dependencies.chrono]
version = "*"
features = ["serde"]

[dependencies.hex]
version = "*"

[dependencies.rayon]
version = "*"

[dependencies.serde]
version = "*"
features = ["derive"]

[dependencies.serde_json]
version = "*"

[dependencies.zip]
version = "=0.6.6"
features = ["deflate"]
default-features = false
