[package]
name = "fimfareader-cli"
version = "0.1.0"
authors = ["Joakim Soderlund <joakim.soderlund@gmail.com>"]
edition = "2021"

[dependencies.fimfareader]
path = ".."

[dependencies.fimfareader-query]
path = "../query"

[dependencies.rustyline]
default-features = false
version = "14"
